services:
  app:
    image: anonyymi/miniboard/app:latest
    pull_policy: build
    build:
      context: .
      dockerfile: docker/miniboard/Dockerfile
      target: dev
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-fs', 'http://localhost:80']
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
    networks:
      - app
    volumes:
      - ./src:/app/src:Z
    ports:
      - "127.0.0.1:8080:80"
    environment:
      XDEBUG_MODE: profile
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      MB_TIMEZONE: Europe/Helsinki
      MB_DB_HOST: mariadb
      MB_DB_NAME: ${DB_NAME}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASS}
      REDIS_HOST: redis
      REDIS_PASS: ${REDIS_PASS}
      CSAM_SCANNER_HOST: csam-scanner
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    restart: always
    networks:
      - app
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_CHARSET: 'utf8'
      MYSQL_COLLATION: 'utf8mb4_unicode_ci'
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    networks:
      - app
    ports:
      - 127.0.0.1:8082:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}

  redis:
    image: redis:7.0-alpine
    restart: always
    command: '--save 60 1 --loglevel verbose --requirepass ${REDIS_PASS}'
    networks:
      - app
    volumes:
      - redis:/data
    ports:
      - '127.0.0.1:6379:6379'
  
  csam-scanner:
    image: anonyymi/miniboard/csam-scanner:latest
    pull_policy: build
    build:
      context: .
      dockerfile: docker/csam-scanner/Dockerfile
    restart: always
    networks:
      - app
    ports:
      - "127.0.0.1:8090:8000"
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ORIGINATOR: localhost
      TOLERANCE: 0.95
    depends_on:
      - mariadb

  test-csam-scanner:
    image: anonyymi/miniboard/csam-scanner:latest
    pull_policy: never
    restart: on-failure
    command: ['bash', '-c', '. /opt/venv/bin/activate && python -m unittest']
    networks:
      - test

networks:
  app:
    driver: bridge
  test:
    driver: bridge

volumes:
  app:
  mariadb:
  redis:
